wandb_version: 1

layer_1:
  desc: null
  value: 128
activation_1:
  desc: null
  value: tanh
layer_2:
  desc: null
  value: 64
activation_2:
  desc: null
  value: tanh
layer_3:
  desc: null
  value: 256
activation_3:
  desc: null
  value: relu
dropout:
  desc: null
  value: 0.5
layer_5:
  desc: null
  value: 256
activation_5:
  desc: null
  value: softmax
optimizer:
  desc: null
  value: adam
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
epoch:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701893877.800104
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 7
      - 16
      - 23
      - 38
      - 39
      4: 3.10.4
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
